Policy/urls.py
from django.urls import include, path
from . import views
from . import views_API

app_name = 'policy'

urlpatterns = [
    path('',
         views.NavBar.as_view(), name='navBar'),
    path('partner/list/',
         views.BusinessPartnerListView.as_view(), name='bp_list'),
    path('partner/detail/<int:pk>/<str:type>/',
         views.BusinessPartnerDetailView.as_view(), name='bp_detail'),
    path('partner/create/',
         views.BusinessPartnerCreateView.as_view(), name='partner_create'),
    path('policy/list/',
         views.PolicyListView.as_view(), name='policy_list'),
    path('policy/detail/<int:pk>/',
         views.PolicyDetailView.as_view(), name='policy_detail'),
    path('policy/<str:product>/create/',
         views.PolicyCreateView.as_view(), name='policy_create'),

    ################################# API View #################################

    path('api/', views_API.APIOverview.as_view(), name='api_overview'),
    path('api/policy/list/', views_API.PolicyListView.as_view(), name='policy-list'),
    path('api/policy/create/', views_API.PolicyCreateView.as_view(),
         name='policy-create/'),
    path('api/policy/detail/<int:pk>/',
         views_API.PolicyDetailView.as_view(), name='policy-detail'),
    path('api/partner/list/', views_API.PartnerListView.as_view(), name='partner-list'),
    path('api/partner/create/', views_API.PartnerCreateView.as_view(),
         name='partner-create/'),
    path('api/partner/detail/<int:pk>/',
         views_API.PartnerDetailView.as_view(), name='partner-detail'),
]

tigerlab_basic_modified/urls.py
from django.contrib import admin
from django.urls import path, include
from Policy import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Policy.urls'))
]

Policy/models.py
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.db import models
from django.urls import reverse
# Create your models here.


class BusinessPartner(models.Model):
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    full_name = models.CharField(max_length=255, null=True, blank=True)
    DOB = models.DateField(null=True, blank=True)
    company_name = models.CharField(max_length=255, null=True, blank=True)
    registration_number = models.CharField(
        max_length=255,  null=True, blank=True)
    email = models.EmailField(max_length=255, unique=True)
    phone = models.CharField(max_length=255)
    role = models.ForeignKey(
        'PartnerRole', on_delete=models.CASCADE, null=False, blank=True)
    bp_Type = models.ForeignKey(
        'PartnerType', on_delete=models.CASCADE, null=False, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.first_name:
            self.full_name = self.first_name + ' ' + self.last_name
        super().save(*args, **kwargs)

    def __str__(self):
        if self.first_name:
            return self.first_name + ' ' + self.last_name
        else:
            return self.company_name


class PartnerRole(models.Model):
    role_name = models.CharField(max_length=255)

    def __str__(self):
        return self.role_name


class PartnerType(models.Model):
    type_name = models.CharField(max_length=255)

    def __str__(self):
        return self.type_name


class Product(models.Model):
    product = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.product


class Policy(models.Model):
    insurance = models.ForeignKey(
        'BusinessPartner', on_delete=models.CASCADE, related_name='insurance_id',  limit_choices_to={'role_id': 3}, default=1)
    agent = models.ForeignKey(
        'BusinessPartner', on_delete=models.CASCADE, related_name='agent_id', limit_choices_to={'role_id': 2}, default=1)
    policy_holder = models.ForeignKey(
        'BusinessPartner', on_delete=models.CASCADE, related_name='holder_id', limit_choices_to={'role_id': 1}, default=1)
    product = models.ForeignKey(
        'Product', on_delete=models.CASCADE, null=False, blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    effective_date = models.DateField()
    period_of_cover = models.DurationField(null=True, blank=True)
    status = models.ForeignKey(
        'PolicyStatus', on_delete=models.CASCADE, default=1)
    transaction_type = models.ForeignKey(
        'PolicyTransactionType', on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.policy_holder.first_name + " " + self.policy_holder.last_name

    def save(self, *args, **kwargs):
        if self.period_of_cover:
            monthsToDays = self.period_of_cover.seconds * 30.436875
            self.period_of_cover = datetime.timedelta(days=monthsToDays)
        super().save(*args, **kwargs)


class PolicyStatus(models.Model):
    status_name = models.CharField(max_length=255)

    def __str__(self):
        return self.status_name


class PolicyTransactionType(models.Model):
    transaction_type = models.CharField(max_length=255)

    def __str__(self):
        return self.transaction_type

Policy/forms.py
import logging
from django.forms import BaseFormSet
from django.forms.models import inlineformset_factory
from django.utils import timezone
from django import forms
from .models import PolicyStatus, PolicyTransactionType, PartnerRole, PartnerType, Product, Policy, BusinessPartner
import datetime
from .signals import new_policy


class InsuranceForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(InsuranceForm, self).__init__(*args, **kwargs)
        self.fields['role'].initial = 3
        self.fields['bp_Type'].initial = 1

    class Meta:
        model = BusinessPartner
        fields = '__all__'

        widgets = {
            'company_name': forms.TextInput(attrs={'class': 'form-control'}),
            'registration_number': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'role': forms.HiddenInput(),
            'bp_Type': forms.HiddenInput()
        }


class AgentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AgentForm, self).__init__(*args, **kwargs)
        self.fields['role'].initial = 2
        self.fields['bp_Type'].initial = 2

    class Meta:
        model = BusinessPartner
        fields = '__all__'

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'DOB': forms.DateInput(format='%d/%m/%Y', attrs={'class': 'form-control inputDOB-agent', 'autocomplete': "off"}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'role': forms.HiddenInput(),
            'bp_Type': forms.HiddenInput()
        }


class HolderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(HolderForm, self).__init__(*args, **kwargs)
        self.fields['role'].initial = 1
        self.fields['bp_Type'].initial = 2

    class Meta:
        model = BusinessPartner
        fields = '__all__'

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'DOB': forms.DateInput(format='%d/%m/%Y', attrs={'class': 'form-control inputDOB', 'autocomplete': "off"}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'role': forms.HiddenInput(),
            'bp_Type': forms.HiddenInput()
        }


class PolicyForm(forms.ModelForm):

    def __init__(self,  *args, **kwargs):
        self.product_id = kwargs.pop('product_id')
        super(PolicyForm, self).__init__(*args, **kwargs)
        self.fields['product'].initial = self.product_id

    def save(self, *args, **kwargs):
        super(PolicyForm, self).save(*args, **kwargs)
        newPolicy = self.instance
        new_policy.send(sender=Policy,
                        policy=newPolicy,
                        holder=newPolicy.policy_holder,
                        insurance=newPolicy.insurance,
                        agent=newPolicy.agent,
                        product=newPolicy.product)

    class Meta:
        model = Policy
        fields = '__all__'

        widgets = {
            'insurance': forms.Select(attrs={'class': 'form-control'}),
            'agent': forms.Select(attrs={'class': 'form-control'}),

            'product': forms.HiddenInput(),
            'effective_date': forms.DateInput(format='%d/%m/%Y', attrs={'class': 'form-control inputEffectiveDate', 'autocomplete': "off"}),
            'period_of_cover': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': "off", 'required': False}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            'transaction_type': forms.Select(attrs={'class': 'form-control'})
        }


PolicyFormSet = inlineformset_factory(
    BusinessPartner,  # parent form
    Policy,  # inline-form
    fk_name='policy_holder',  # specify the foreign key that links both model
    form=PolicyForm,  # set a custom form for the inline form
    extra=1)  # how many inline-forms are sent to the template by default

Policy/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.shortcuts import render
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from .models import PolicyStatus, PolicyTransactionType, PartnerRole, PartnerType, Product, Policy, BusinessPartner
from django.db.models.functions import Concat
from django.db.models import F, Value
from django.db import connection
from itertools import chain
import datetime
from .forms import PolicyForm, PolicyFormSet, HolderForm, InsuranceForm, AgentForm
from django.views.generic import CreateView
from .signals import new_policy

# Create your views here.


class NavBar(View):
    def get(self, request):
        product = Product.objects.all()
        context = {'Products': product}
        return render(request, 'Policy/index.html', context)


class BusinessPartnerListView(View):
    def get(self, request):
        product = Product.objects.all()
        partners = BusinessPartner.objects.all().order_by('-id')
        context = {'BusinessPartners': partners, 'Products': product}

        return render(request, 'Policy/partnerList.html', context)


class BusinessPartnerDetailView(View):
    def get(self, request, pk, type):
        product = Product.objects.all()
        detail = BusinessPartner.objects.get(id=pk)
        context = {'partner': detail, 'Products': product}

        return render(request, 'Policy/partnerDetail.html', context)


class BusinessPartnerCreateView(View):
    def get(self, request):
        product = Product.objects.all()
        agentForm = AgentForm()
        insuranceForm = InsuranceForm()

        context = {
            'Products': product,
            'insuranceForm': insuranceForm,
            'agentForm': agentForm
        }

        return render(request, 'Policy/partnerCreation.html', context)

    def post(self, request, *args, **kwargs):
        product = Product.objects.all()
        context = {'Products': product}

        if 'insurance' in request.POST:
            agentForm = AgentForm()
            insuranceForm = InsuranceForm(request.POST)

            if insuranceForm.is_valid():
                insuranceForm.save()
                return HttpResponseRedirect(reverse('policy:bp_list'))
            else:
                context['insuranceForm'] = insuranceForm
                context['agentForm'] = agentForm

        elif 'agent' in request.POST:
            insuranceForm = InsuranceForm()
            agentForm = AgentForm(request.POST)

            if agentForm.is_valid():
                agentForm.save()
                return HttpResponseRedirect(reverse('policy:bp_list'))
            else:
                context['agentForm'] = agentForm
                context['insuranceForm'] = insuranceForm

        return render(request, 'Policy/partnerCreation.html', context)


class PolicyListView(View):

    def get(self, request):
        product = Product.objects.all()
        policyList = Policy.objects.all().order_by('-id')
        context = {'Policies': policyList, 'Products': product}

        return render(request, 'Policy/policyList.html', context)


class PolicyDetailView(View):

    def get(self, request, pk):
        product = Product.objects.all()
        policyDetail = Policy.objects.get(id=pk)
        if policyDetail.period_of_cover:
            end_date = policyDetail.effective_date + policyDetail.period_of_cover
            context = {'Policy': policyDetail,
                       'End_Date': end_date, 'Products': product}
        else:
            context = {'Policy': policyDetail, 'Products': product}

        return render(request, 'Policy/policyDetail.html', context)


class PolicyCreateView(CreateView):
    model = Policy
    template_name = 'Policy/policyCreation.html'
    form_class = HolderForm
    success_url = '/policy/list'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(PolicyCreateView, self).get_context_data(**kwargs)
        # for navbar product list
        context['Products'] = Product.objects.all()
        # get URL params
        context['productName'] = self.kwargs['product'].replace('-', ' ')

        product_id = Product.objects.get(
            product=self.kwargs['product'].replace('-', ' '))
        if self.request.POST:
            context['policy'] = PolicyFormSet(self.request.POST,  form_kwargs={
                'product_id': product_id.id})
        else:
            context['policy'] = PolicyFormSet(
                form_kwargs={'product_id': product_id.id})

        return context

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance and its inline
        formsets with the passed POST variables and then checking them for
        validity.
        """

        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        context = self.get_context_data()
        policy_form = context['policy']
        if (form.is_valid() and policy_form.is_valid()):
            return self.form_valid(form, policy_form)
        else:

            return self.form_invalid(form, policy_form)

    def form_valid(self, form, policy_form):
        """
        Called if all forms are valid. Creates a Holder instance along with
        associated policy and then redirects to a
        success page.
        """
        self.object = form.save()
        policy_form.instance = self.object
        policy_form.save()

        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, policy_form):
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form,
                                  policy=policy_form))

    # def get_form_kwargs(self):
    #     kwargs = super(PolicyCreateView, self).get_form_kwargs()
    #     # update the kwargs for the form init method with yours
    #     # kwargs.update(self.kwargs)  # self.kwargs contains all url conf params
    #     product_id = Product.objects.values(
    #         'id').get(product=self.kwargs['product'])
    #     kwargs["product_id"] = product_id.id
    #     return kwargs

Policy/templates/Policy/index.html
{% load static %} {% load poll_extras %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css" />
    <link rel="stylesheet" type="text/css" href="https://npmcdn.com/flatpickr/dist/themes/material_green.css" />

    <link rel="stylesheet" href="{% static 'Policy/index.css' %}" />
    <!-- Latest compiled and minified CSS -->
  </head>
  <body>
    <div class="container" style="top: 50px; position: relative">
      <nav class="navbar navbar-expand-lg" style="background: black; border-radius: 4px">
        <span class="navbar-brand" style="font-size: 35px; color: white; padding: 0px">
          <strong> i<span style="color: #ffab40">2</span>go</strong></span
        >

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                style="color: white; cursor: pointer"
              >
                &nbsp; &nbsp;<i class="fab fa-product-hunt" style="font-size: 28px; cursor: pointer; font-weight: bold">
                  &nbsp;Create
                </i>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for product in Products %}
                <a class="dropdown-item" href="{% url 'policy:policy_create' product.product|dashURL %}"
                  >{{product.product}}</a
                >
                {% endfor %}
              </div>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                style="color: white; cursor: pointer"
              >
                <i class="fas fa-search" style="font-size: 28px; cursor: pointer"> &nbsp;Search </i>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'policy:bp_list' %}">Business Partner</a>
                <a class="dropdown-item" href="{% url 'policy:policy_list' %}">Policy</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>
    </div>

    <div class="container tabless" style="position: absolute; top: 180px; right: 170px; margin-bottom: 50px">
      {% block policyList_section %} {% endblock %}
    </div>

    <div class="container" style="position: absolute; top: 180px; right: 190px; margin-bottom: 50px">
      {% block businessPartnersList_section %}{% endblock %}
    </div>

    <div class="container" style="position: absolute; top: 180px; right: 190px; margin-bottom: 50px">
      {% block createPolicy %}{% endblock %}
    </div>

    <div class="container" style="position: absolute; top: 180px; right: 190px; margin-bottom: 50px">
      {% block createPartner %}{% endblock %}
    </div>

    <div class="container" style="position: absolute; top: 180px; right: 190px; margin-bottom: 50px">
      {% block policyDetail_page %}{% endblock %}
    </div>

    <div class="container" style="position: absolute; top: 180px; right: 200px; margin-bottom: 50px">
      {% block BP_Detail_page %}{% endblock %}
    </div>
  </body>
  <script src="https://kit.fontawesome.com/e881600de5.js" crossorigin="anonymous"></script>
  <script
    src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"
  ></script>
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script src="{% static 'Policy/index.js' %}"></script>
</html>

Policy/templates/Policy/partnerDetail.html
{% extends "Policy/index.html"%} {% block BP_Detail_page%}
<div class="card">
  <div class="card-header" style="background: black; color: white">
    <a href="{% url 'policy:bp_list' %}"
      ><i class="fas fa-arrow-circle-left" style="font-size: 25px; color: rgb(230, 52, 52)"></i
    ></a>
    <h2 style="display: inline">&nbsp; Business Partner ({{partner.role}})</h2>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6 font-weight-bold">BP ID</div>
      <div class="col-sm-6">{{partner.id}}</div>
    </div>

    {% if partner.role.role_name == 'Policy Holder' or partner.role.role_name == 'Agent'%}
    <div class="row">
      <div class="col-sm-6 font-weight-bold">First name</div>
      <div class="col-sm-6">{{partner.first_name}}</div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Last name</div>
      <div class="col-sm-6">{{partner.last_name}}</div>
    </div>

    <hr />
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Date of Birth</div>
      <div class="col-sm-6">{{partner.DOB|date:'d/m/Y'}}</div>
    </div>
    <hr />

    {% else %}
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Company Name</div>
      <div class="col-sm-6">{{partner.company_name}}</div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Registration Number</div>
      <div class="col-sm-6">{{partner.registration_number}}</div>
    </div>
    <hr />

    {% endif %}
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Email</div>
      <div class="col-sm-6">{{partner.email}}</div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Mobile</div>
      <div class="col-sm-6">{{partner.phone}}</div>
    </div>
  </div>
</div>
{% endblock %}

Policy/templates/Policy/partnerList.html
{% extends "Policy/index.html"%} {% block businessPartnersList_section%} {% load poll_extras %}
<a href="{% url 'policy:partner_create' %}"><i class="fas fa-user-plus"></i></a>
<table class="table table-striped table-hover">
  <thead style="background: black; color: white">
    <tr>
      <th scope="col">No.</th>
      <th scope="col">ID</th>
      <th scope="col">Name/Company</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Role</th>
      <th scope="col">Type</th>
    </tr>
  </thead>
  <tbody>
    {% for BP in BusinessPartners %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <th scope="row">
        <a href="{% url 'policy:bp_detail' BP.id BP.role.role_name|dashURL %}">{{BP.id}}</a>
      </th>
      <td>{% firstof BP.full_name BP.company_name %}</td>
      <td>{{BP.email}}</td>
      <td>{{BP.phone}}</td>
      <td>{{BP.role}}</td>
      <td>{{BP.bp_Type}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

Policy/templates/Policy/policyDetail.html
{% extends "Policy/index.html"%} {% block policyDetail_page%}
<div class="card">
  <div class="card-header" style="background: black; color: white">
    <a href="{% url 'policy:policy_list' %}"
      ><i class="fas fa-arrow-circle-left" style="font-size: 25px; color: rgb(230, 52, 52)"></i
    ></a>
    <h2 style="display: inline">&nbsp; Policy ID: {{Policy.id}}</h2>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Insurance</div>
      <div class="col-sm-6">{{Policy.insurance.company_name}}</div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Product</div>
      <div class="col-sm-6">{{Policy.product.product}}</div>
    </div>
    <hr />
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Creation Date</div>
      <div class="col-sm-6">{{Policy.created_date|date:'d/m/Y g:i a'}}</div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Updated Date</div>
      <div class="col-sm-6">{{Policy.updated_date|date:'d/m/Y g:i a'}}</div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Effective Date</div>
      <div class="col-sm-6">{{Policy.effective_date|date:'d/m/Y'}}</div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Period of Cover</div>
      <div class="col-sm-6">{{Policy.effective_date|date:'d/m/Y'}} to {{End_Date|date:'d/m/Y'}}</div>
    </div>

    <hr />
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Client</div>
      <div class="col-sm-6">
        <a href="{% url 'policy:bp_detail' Policy.policy_holder.id Policy.policy_holder.role %}"
          >{{Policy.policy_holder.full_name}}</a
        >
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Email</div>
      <div class="col-sm-6">{{Policy.policy_holder.email}}</div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Mobile No</div>
      <div class="col-sm-6">{{Policy.policy_holder.phone}}</div>
    </div>
    <hr />
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Agent</div>
      <div class="col-sm-6">{{Policy.agent.full_name}}</div>
    </div>
    <hr />
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Status</div>
      <div class="col-sm-6">{{Policy.status.status_name}}</div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Transaction Type</div>
      <div class="col-sm-6">{{Policy.transaction_type.transaction_type}}</div>
    </div>
  </div>
</div>
<br />
<br />
<br />

<div class="card">
  <div class="card-header" style="background: black; color: white">
    <h2 style="display: inline">Partner</h2>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Agent</div>
      <div class="col-sm-6">
        <a href="{% url 'policy:bp_detail' Policy.agent.id Policy.agent.role %}">{{Policy.agent.full_name}}</a>
      </div>
    </div>
    <hr />
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Client</div>
      <div class="col-sm-6">
        <a href="{% url 'policy:bp_detail' Policy.policy_holder.id Policy.policy_holder.role %}"
          >{{Policy.policy_holder.full_name}}</a
        >
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Email</div>
      <div class="col-sm-6">{{Policy.policy_holder.email}}</div>
    </div>
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Mobile No</div>
      <div class="col-sm-6">{{Policy.policy_holder.phone}}</div>
    </div>
    <hr />
    <div class="row">
      <div class="col-sm-6 font-weight-bold">Date of Birth</div>
      <div class="col-sm-6">{{Policy.policy_holder.DOB|date:'d/m/Y'}}</div>
    </div>
  </div>
</div>
{% endblock %}

Policy/templates/Policy/policyList.html
{% extends "Policy/index.html"%} {% block policyList_section%}
<table class="table table-striped table-hover">
  <thead style="background: black; color: white">
    <tr>
      <th scope="col">No.</th>
      <th scope="col">Creation Date</th>
      <th scope="col">Creation Time</th>
      <th scope="col">Updated Date</th>
      <th scope="col">Reference No</th>
      <th scope="col">Client</th>
      <th scope="col">Product</th>
      <th scope="col">Agent</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    {% for policy in Policies %} {{policy.policy_holder_id.full_name}}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{policy.created_date|date:'d/m/Y'}}</td>
      <td>{{policy.created_date|date:'g:i a'}}</td>
      <td>{{policy.updated_date|date:'d/m/Y'}}</td>
      <td><a href="{% url 'policy:policy_detail' pk=policy.id %}">{{policy.id}}</a></td>
      <td>{{policy.policy_holder.full_name}}</td>
      <td>{{policy.product.product}}</td>
      <td>{{policy.agent.full_name}}</td>
      <td>{{policy.status}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}